project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Owen Beelders
    left:
      - href: about.qmd
      - text: cv
        href: /cv/obeelders12142024.pdf
      - href: blog/index.qmd

    tools:
    - icon: github
      text: Github
      href: https://github.com/OwenBeelders
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/owenbeelders/
      
format:
  html:
    backgroundcolor: "white"
    fontcolor: "black"
    linkcolor: "orange"
    mainfont: "Source Sans Pro"
    fontsize: "18px"
    theme: [cosmo, styles.scss]

